# Generated by Django 2.1.7 on 2019-02-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='tbl_data',
        ),
    ]
