# Generated by Django 2.1.5 on 2019-02-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20190212_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_data',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tbl_data',
            name='title',
        ),
        migrations.AddField(
            model_name='tbl_data',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tbl_data',
            name='mobile',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='tbl_data',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
