# Generated by Django 2.1.5 on 2019-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20190214_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_data',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
