# Generated by Django 2.1.7 on 2019-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='title',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Firstname',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Lastname',
            field=models.CharField(default='lastname', max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Mobile',
            field=models.CharField(default='123', max_length=11),
        ),
    ]
