# Generated by Django 2.1.7 on 2019-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_auto_20190220_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Lastname',
            field=models.CharField(max_length=255),
        ),
    ]
