# Generated by Django 2.1.7 on 2019-02-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=11)),
                ('profile_pic', models.FileField(default='set.jpg', upload_to='images/')),
            ],
        ),
    ]
